
service: using-http-cors-example

provider:
  name: aws
  runtime: nodejs6.10

functions:
  hello:
    handler: handler.functionWithCors
    events:
      - http:
          path: function-with-cors
          method: post
          # WORKSHOP_START
          # Step 1. In this_file, Add cors settings to `http` event. http://bit.ly/2mkgV4P
          # WORKSHOP_END
          # FINAL_START
          cors: true
          # FINAL_END
