
service: using-env-variables-example

provider:
  name: aws
  runtime: nodejs6.10
  # Step 1. In this_file, add an environment variable for all functions to access. http://bit.ly/2yVp4CR

functions:
  foo:
    handler: handler.foo
    events:
      - http:
          path: foo
          method: get
  bar:
    handler: handler.bar
    # Step 2. add an environment variable only `bar` function to access. http://bit.ly/2yVp4CR
    events:
      - http:
          path: bar
          method: get

# Step 5. After adding your environment variables to serverless.yml and handler.js.
# Run `sls deploy` to deploy the service #
