
service: using-http-cors-example

provider:
  name: aws
  runtime: nodejs6.10

functions:
  hello:
    handler: handler.functionWithCors
    events:
      - http:
          path: function-with-cors
          method: post
          # Add cors settings. docs link: http://bit.ly/2mkgV4P
