
service: using-serverless-plugins

# FINAL_START
plugins:
  - serverless-manifest-plugin

custom:
  output:
    file: .serverless/manifest.json
# FINAL_END

provider:
  name: aws
  runtime: nodejs6.10

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
