
service: using-multiple-stages

provider:
  name: aws
  runtime: nodejs6.10
  # WORKSHOP_START
  # Step 3. In this_file, set the stage key to a serverless variable. Information on variables: http://bit.ly/2zw4DM9
  # WORKSHOP_END

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
