
service: aws-s3-event-example

# Define a `custom` block and make a bucketName

provider:
  name: aws
  runtime: nodejs6.10
  # Expose the bucketName to `environment` variables
  # Create the IAM role `iamRoleStatements` needed to `GetObject` & `PutObject`
  # Narrow the scope of the permission to the two buckets in this service

functions:
  save:
    handler: save.saveImage
    # Attach the save function to an http POST endpoint
    events:
      - http:
          path: save-image
          method: post
          cors: true
  # Attach the save function to an http POST endpoint
  resize:
    handler: resize.handleImageResize
  # attach the s3 event to this function and trigger when images are added to bucket
  # a.k.a the `ObjectCreated` s3 event. docs link http://bit.ly/2zyiRMB

# Add an additional bucket in `resources`. This bucket will be used for storing the resized images
