
service: event-driven-app

provider:
  name: aws
  runtime: nodejs6.10
  # WORKSHOP_START
  # Define the IAM role needed for the function to access the newly created dynamo table
  # See final code for example
  # WORKSHOP_END
  # FINAL_START
  environment:
    # Here we reference the table name defined below. This is a cloud formation ref
    MY_TABLE: { Ref: myDynamoTable }
  # Here we add a custom IAM statement to allow the function to access our dynamoDB Table
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:Scan
      Resource: { Fn::GetAtt: [ myDynamoTable, Arn ] }
  # FINAL_END

functions:
  create:
    handler: handler.create
    events:
      - http:
          path: create
          method: post
          cors: true
  scan:
    handler: handler.scan
    events:
      - http:
          path: scan
          method: post
          cors: true

# WORKSHOP_START
# use the resources block to define a dynamoDB table
resources:
# WORKSHOP_END
# FINAL_START
resources:
  Resources:
    myDynamoTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: 'my-table-name'
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
# FINAL_END
