
service: my-first-service

provider:
  name: aws
  runtime: nodejs6.10

functions:
  hello:
    handler: handler.hello
    # WORKSHOP_START
    # Add an http GET event to trigger this function
    # docs link: http://bit.ly/2mkgV4P
    # WORKSHOP_END
    # FINAL_START
    events:
      - http:
          path: hello
          method: get
    # FINAL_END
